create table Action (id int8 not null, method varchar(255), type varchar(255), businessRule_id int8, primary key (id));
create table Action_TemplateValue (Action_id int8 not null, detail_id int8 not null, unique (detail_id));
create table Attachment (id int8 not null, primary key (id));
create table BusinessRule (id int8 not null, description varchar(255), enabled bool not null, name varchar(255), onCreate bool not null, onDelete bool not null, onUpdate bool not null, type varchar(255), primary key (id));
create table Category (id int8 not null, name varchar(255), parent_id int8, primary key (id));
create table Client (id int8 not null, company_id int8, priority_id int8, primary key (id));
create table Company (id int8 not null, name varchar(255), primary key (id));
create table Detail (id int8 not null, date timestamp, message varchar(255), incident_id int8, user_id int8, primary key (id));
create table Impact (id int8 not null, description varchar(255), primary key (id));
create table Incident (id int8 not null, description varchar(255), dueDate timestamp, openedDate timestamp, resolution varchar(255), respondedDate timestamp, status varchar(255), template bool not null, updatedAt timestamp, category_id int8, client_id int8, priority_id int8, responsable_id int8, primary key (id));
create table Incident_Attachment (Incident_id int8 not null, attachments_id int8 not null, unique (attachments_id));
create table MailNotification (id int8 not null, address varchar(255), body varchar(255), subject varchar(255), template bool not null, primary key (id));
create table Priority (id int8 not null, description varchar(255), duration int4 not null, response int4 not null, impact_id int8, urgency_id int8, primary key (id));
create table Staff (id int8 not null, primary key (id));
create table Task (id int8 not null, detail_type varchar(255), detail_id int8 not null, duoDate timestamp, executed bool not null, primary key (id));
create table TemplateValue (id int8 not null, field varchar(255), value varchar(255), primary key (id));
create table Urgency (id int8 not null, description varchar(255), primary key (id));
create table WorkOrder (id int8 not null, description varchar(255), template bool not null, incident_id int8, primary key (id));
create table conditions (id int8 not null, comparisonOperator varchar(255), expression1 varchar(255), expression2 varchar(255), logicalOperator varchar(255), businessRule_id int8, primary key (id));
create table users (id int8 not null, active bool not null, email varchar(255) not null unique, name varchar(255), password varchar(255), role varchar(255), primary key (id));
alter table Action add constraint FK74946A569B66A0A7 foreign key (businessRule_id) references BusinessRule;
alter table Action_TemplateValue add constraint FKE0F32ECE84B3C007 foreign key (Action_id) references Action;
alter table Action_TemplateValue add constraint FKE0F32ECEE4694233 foreign key (detail_id) references TemplateValue;
alter table Category add constraint FK6DD211EA983A09B foreign key (parent_id) references Category;
alter table Client add constraint FK7877DFEB9CCC9A33 foreign key (id) references users;
alter table Client add constraint FK7877DFEBEEBE842D foreign key (company_id) references Company;
alter table Client add constraint FK7877DFEBF5679207 foreign key (priority_id) references Priority;
alter table Detail add constraint FK79CF047194077B27 foreign key (user_id) references users;
alter table Detail add constraint FK79CF047188049B47 foreign key (incident_id) references Incident;
alter table Incident add constraint FK909A8F2F5679207 foreign key (priority_id) references Priority;
alter table Incident add constraint FK909A8F289C59BC7 foreign key (category_id) references Category;
alter table Incident add constraint FK909A8F2B475BE7 foreign key (client_id) references Client;
alter table Incident add constraint FK909A8F247F9B02F foreign key (responsable_id) references Staff;
alter table Incident_Attachment add constraint FK447336B07815D4BA foreign key (attachments_id) references Attachment;
alter table Incident_Attachment add constraint FK447336B088049B47 foreign key (Incident_id) references Incident;
alter table Priority add constraint FKBE62DDC461EEA607 foreign key (impact_id) references Impact;
alter table Priority add constraint FKBE62DDC4F61380AD foreign key (urgency_id) references Urgency;
alter table Staff add constraint FK4C7D2C09CCC9A33 foreign key (id) references users;
alter table WorkOrder add constraint FKB78FB29D88049B47 foreign key (incident_id) references Incident;
alter table conditions add constraint FKC88436B89B66A0A7 foreign key (businessRule_id) references BusinessRule;
create sequence hibernate_sequence;
