alter table Action drop foreign key FK74946A569B66A0A7;
alter table Action_TemplateValue drop foreign key FKE0F32ECE84B3C007;
alter table Action_TemplateValue drop foreign key FKE0F32ECEE4694233;
alter table Category drop foreign key FK6DD211EA983A09B;
alter table Client drop foreign key FK7877DFEB9CCC9A33;
alter table Client drop foreign key FK7877DFEBEEBE842D;
alter table Client drop foreign key FK7877DFEBF5679207;
alter table Detail drop foreign key FK79CF047194077B27;
alter table Detail drop foreign key FK79CF047188049B47;
alter table Incident drop foreign key FK909A8F261EEA607;
alter table Incident drop foreign key FK909A8F289C59BC7;
alter table Incident drop foreign key FK909A8F2B475BE7;
alter table Incident drop foreign key FK909A8F247F9B02F;
alter table Incident drop foreign key FK909A8F2F61380AD;
alter table Incident_Attachment drop foreign key FK447336B07815D4BA;
alter table Incident_Attachment drop foreign key FK447336B088049B47;
alter table Priority drop foreign key FKBE62DDC461EEA607;
alter table Priority drop foreign key FKBE62DDC4F61380AD;
alter table Staff drop foreign key FK4C7D2C09CCC9A33;
alter table WorkOrder drop foreign key FKB78FB29D88049B47;
alter table conditions drop foreign key FKC88436B89B66A0A7;
drop table if exists Action;
drop table if exists Action_TemplateValue;
drop table if exists Attachment;
drop table if exists BusinessRule;
drop table if exists Category;
drop table if exists Client;
drop table if exists Company;
drop table if exists Detail;
drop table if exists Impact;
drop table if exists Incident;
drop table if exists Incident_Attachment;
drop table if exists MailNotification;
drop table if exists Priority;
drop table if exists Staff;
drop table if exists Task;
drop table if exists TemplateValue;
drop table if exists Urgency;
drop table if exists User;
drop table if exists WorkOrder;
drop table if exists conditions;
create table Action (id bigint not null auto_increment, method varchar(255), type varchar(255), businessRule_id bigint, primary key (id)) ENGINE=InnoDB;
create table Action_TemplateValue (Action_id bigint not null, detail_id bigint not null, unique (detail_id)) ENGINE=InnoDB;
create table Attachment (id bigint not null auto_increment, primary key (id)) ENGINE=InnoDB;
create table BusinessRule (id bigint not null auto_increment, description varchar(255), enabled bit not null, name varchar(255), onCreate bit not null, onDelete bit not null, onUpdate bit not null, type varchar(255), primary key (id)) ENGINE=InnoDB;
create table Category (id bigint not null auto_increment, name varchar(255), parent_id bigint, primary key (id)) ENGINE=InnoDB;
create table Client (id bigint not null, company_id bigint, priority_id bigint, primary key (id)) ENGINE=InnoDB;
create table Company (id bigint not null auto_increment, name varchar(255), primary key (id)) ENGINE=InnoDB;
create table Detail (id bigint not null auto_increment, date datetime, message varchar(255), incident_id bigint, user_id bigint, primary key (id)) ENGINE=InnoDB;
create table Impact (id bigint not null auto_increment, description varchar(255), primary key (id)) ENGINE=InnoDB;
create table Incident (id bigint not null auto_increment, description varchar(255), dueDate datetime, openedDate datetime, resolution varchar(255), respondedDate datetime, status varchar(255), template bit not null, updatedAt datetime, category_id bigint, client_id bigint, impact_id bigint, responsable_id bigint, urgency_id bigint, primary key (id)) ENGINE=InnoDB;
create table Incident_Attachment (Incident_id bigint not null, attachments_id bigint not null, unique (attachments_id)) ENGINE=InnoDB;
create table MailNotification (id bigint not null auto_increment, address varchar(255), body varchar(255), subject varchar(255), template bit not null, primary key (id)) ENGINE=InnoDB;
create table Priority (id bigint not null auto_increment, description varchar(255), duration bigint not null, response bigint not null, impact_id bigint, urgency_id bigint, primary key (id)) ENGINE=InnoDB;
create table Staff (id bigint not null, primary key (id)) ENGINE=InnoDB;
create table Task (id bigint not null auto_increment, detail_type varchar(255), detail_id bigint not null, duoDate datetime, executed bit not null, primary key (id)) ENGINE=InnoDB;
create table TemplateValue (id bigint not null auto_increment, field varchar(255), value varchar(255), primary key (id)) ENGINE=InnoDB;
create table Urgency (id bigint not null auto_increment, description varchar(255), primary key (id)) ENGINE=InnoDB;
create table User (id bigint not null auto_increment, active bit not null, email varchar(255) not null unique, name varchar(255), password varchar(255), role varchar(255), primary key (id)) ENGINE=InnoDB;
create table WorkOrder (id bigint not null auto_increment, description varchar(255), template bit not null, incident_id bigint, primary key (id)) ENGINE=InnoDB;
create table conditions (id bigint not null auto_increment, comparisonOperator varchar(255), expression1 varchar(255), expression2 varchar(255), logicalOperator varchar(255), businessRule_id bigint, primary key (id)) ENGINE=InnoDB;
alter table Action add index FK74946A569B66A0A7 (businessRule_id), add constraint FK74946A569B66A0A7 foreign key (businessRule_id) references BusinessRule (id);
alter table Action_TemplateValue add index FKE0F32ECE84B3C007 (Action_id), add constraint FKE0F32ECE84B3C007 foreign key (Action_id) references Action (id);
alter table Action_TemplateValue add index FKE0F32ECEE4694233 (detail_id), add constraint FKE0F32ECEE4694233 foreign key (detail_id) references TemplateValue (id);
alter table Category add index FK6DD211EA983A09B (parent_id), add constraint FK6DD211EA983A09B foreign key (parent_id) references Category (id);
alter table Client add index FK7877DFEB9CCC9A33 (id), add constraint FK7877DFEB9CCC9A33 foreign key (id) references User (id);
alter table Client add index FK7877DFEBEEBE842D (company_id), add constraint FK7877DFEBEEBE842D foreign key (company_id) references Company (id);
alter table Client add index FK7877DFEBF5679207 (priority_id), add constraint FK7877DFEBF5679207 foreign key (priority_id) references Priority (id);
alter table Detail add index FK79CF047194077B27 (user_id), add constraint FK79CF047194077B27 foreign key (user_id) references User (id);
alter table Detail add index FK79CF047188049B47 (incident_id), add constraint FK79CF047188049B47 foreign key (incident_id) references Incident (id);
alter table Incident add index FK909A8F261EEA607 (impact_id), add constraint FK909A8F261EEA607 foreign key (impact_id) references Impact (id);
alter table Incident add index FK909A8F289C59BC7 (category_id), add constraint FK909A8F289C59BC7 foreign key (category_id) references Category (id);
alter table Incident add index FK909A8F2B475BE7 (client_id), add constraint FK909A8F2B475BE7 foreign key (client_id) references Client (id);
alter table Incident add index FK909A8F247F9B02F (responsable_id), add constraint FK909A8F247F9B02F foreign key (responsable_id) references Staff (id);
alter table Incident add index FK909A8F2F61380AD (urgency_id), add constraint FK909A8F2F61380AD foreign key (urgency_id) references Urgency (id);
alter table Incident_Attachment add index FK447336B07815D4BA (attachments_id), add constraint FK447336B07815D4BA foreign key (attachments_id) references Attachment (id);
alter table Incident_Attachment add index FK447336B088049B47 (Incident_id), add constraint FK447336B088049B47 foreign key (Incident_id) references Incident (id);
alter table Priority add index FKBE62DDC461EEA607 (impact_id), add constraint FKBE62DDC461EEA607 foreign key (impact_id) references Impact (id);
alter table Priority add index FKBE62DDC4F61380AD (urgency_id), add constraint FKBE62DDC4F61380AD foreign key (urgency_id) references Urgency (id);
alter table Staff add index FK4C7D2C09CCC9A33 (id), add constraint FK4C7D2C09CCC9A33 foreign key (id) references User (id);
alter table WorkOrder add index FKB78FB29D88049B47 (incident_id), add constraint FKB78FB29D88049B47 foreign key (incident_id) references Incident (id);
alter table conditions add index FKC88436B89B66A0A7 (businessRule_id), add constraint FKC88436B89B66A0A7 foreign key (businessRule_id) references BusinessRule (id);
